### ISSUE TITLE
Webpack 5 Deprecation Warning: SingleEntryPlugin was renamed to EntryPlugin

### ISSUE THREAD

**Issue by sphilee** [shadowwalker/next-pwa#117]
# Summary
Webpack 5 Deprecation Warning: SingleEntryPlugin was renamed to EntryPlugin

# How To Reproduce

1. Clone https://github.com/vercel/next.js/tree/canary/examples/progressive-web-app

2. yarn install && yarn build && yarn start
3. See error

# Screenshots

```cmd
(node:4157) [DEP_WEBPACK_SINGLE_ENTRY_PLUGIN] DeprecationWarning: SingleEntryPlugin was renamed to EntryPlugin
    at get SingleEntryPlugin (/home/vito/Development/MyProject/node_modules/webpack/lib/index.js:246:4)
    at Function.SingleEntryPlugin (/home/vito/Development/MyProject/node_modules/webpack/lib/util/memorize.js:22:13)
    at Object.<anonymous> (/home/vito/Development/MyProject/node_modules/workbox-webpack-plugin/build/inject-manifest.js:15:3)
    at Module._compile (/home/vito/Development/MyProject/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (/home/vito/Development/MyProject/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/home/vito/Development/MyProject/node_modules/workbox-webpack-plugin/build/index.js:12:24)
    at Module._compile (/home/vito/Development/MyProject/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (/home/vito/Development/MyProject/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
```

# Additional Context

Please update to workbox-webpack-plugin v6.x
https://github.com/GoogleChrome/workbox/issues/2669

**Comment by shadowwalker** [comment]
Try `yarn add next-pwa@beta`, see if that works for you.
